/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as AlertsAlertIdRouteImport } from './routes/alerts.$alertId'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => ProgramsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const AlertsAlertIdRoute = AlertsAlertIdRouteImport.update({
  id: '/$alertId',
  path: '/$alertId',
  getParentRoute: () => AlertsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/insights': typeof InsightsRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/insights': typeof InsightsRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/insights': typeof InsightsRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/clients'
    | '/insights'
    | '/programs'
    | '/alerts/$alertId'
    | '/clients/$clientId'
    | '/programs/$programId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/clients'
    | '/insights'
    | '/programs'
    | '/alerts/$alertId'
    | '/clients/$clientId'
    | '/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/clients'
    | '/insights'
    | '/programs'
    | '/alerts/$alertId'
    | '/clients/$clientId'
    | '/programs/$programId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/alerts/$alertId': {
      id: '/alerts/$alertId'
      path: '/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AlertsAlertIdRouteImport
      parentRoute: typeof AlertsRoute
    }
  }
}

interface AlertsRouteChildren {
  AlertsAlertIdRoute: typeof AlertsAlertIdRoute
}

const AlertsRouteChildren: AlertsRouteChildren = {
  AlertsAlertIdRoute: AlertsAlertIdRoute,
}

const AlertsRouteWithChildren =
  AlertsRoute._addFileChildren(AlertsRouteChildren)

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface ProgramsRouteChildren {
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  InsightsRoute: InsightsRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
