/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => ProgramsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/programs'
    | '/clients/$clientId'
    | '/programs/$programId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/programs'
    | '/clients/$clientId'
    | '/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/programs'
    | '/clients/$clientId'
    | '/programs/$programId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  ProgramsRoute: typeof ProgramsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface ProgramsRouteChildren {
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRouteWithChildren,
  ProgramsRoute: ProgramsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
